/* ap-english.js — original AP English Language & Literature reference content for
   SkoolToolz. ALL CONTENT IS ORIGINAL, WRITTEN FOR SKOOLTOOLZ (nothing lifted from the
   exam, a textbook, or any copyrighted work — every example sentence below is invented
   for this glossary) — same integrity bar as ap-psych.js / ap-packs.js. Loaded once via
   a <script> tag on first open of the AP English tool (mirrors ap-psych.js — a <script>
   tag rather than fetch() so it also works from a local file:// copy), then cached on
   window.APEnglish for the session. */
(function () {

  /* ───────────────────────────── Categories ─────────────────────────────
     Five groups spanning both AP Lang (rhetoric/argument) and AP Lit
     (literary/poetic/narrative technique). */
  const CATEGORIES = [
    { id: 'rhetorical', label: 'Rhetorical Devices' },
    { id: 'argument',   label: 'Argument & Appeals' },
    { id: 'literary',   label: 'Literary Devices' },
    { id: 'sound',      label: 'Sound & Poetic Devices' },
    { id: 'narrative',  label: 'Narrative Elements & Style' },
  ];

  /* ───────────────────────────── Terms ─────────────────────────────
     Each term: { term, category, definition, example }. Definitions are concise
     and original; examples are short, invented sentences written to illustrate
     the device (never quoted from a real text). */
  const TERMS = [
    /* ---------- Rhetorical devices ---------- */
    { term: 'Anaphora', category: 'rhetorical',
      definition: 'Repeating a word or phrase at the start of successive clauses or sentences for emphasis and rhythm.',
      example: '"We will train harder. We will practice longer. We will show up when no one is watching."' },
    { term: 'Epistrophe', category: 'rhetorical',
      definition: 'Repeating a word or phrase at the end of successive clauses or sentences.',
      example: '"When the funding disappeared, the coaches stayed. When the gym flooded, the coaches stayed."' },
    { term: 'Chiasmus', category: 'rhetorical',
      definition: 'Reversing the grammatical structure of two parallel phrases (an ABBA pattern) to create a mirrored, memorable effect.',
      example: '"He worked to live, and lived to work."' },
    { term: 'Antithesis', category: 'rhetorical',
      definition: 'Placing two contrasting ideas next to each other in parallel grammatical structure to sharpen the contrast.',
      example: '"The proposal was short on details but long on promises."' },
    { term: 'Rhetorical question', category: 'rhetorical',
      definition: 'A question asked to make a point or provoke thought, not to request an actual answer.',
      example: '"Who among us wouldn\'t want a fairer schedule?"' },
    { term: 'Asyndeton', category: 'rhetorical',
      definition: 'Omitting conjunctions between a series of related clauses or words to speed up the rhythm and add urgency.',
      example: '"She grabbed her bag, sprinted the hallway, hit the door, made the bus."' },
    { term: 'Polysyndeton', category: 'rhetorical',
      definition: 'Using more conjunctions than necessary between a series of clauses or words, slowing the rhythm and stacking emphasis.',
      example: '"We packed the tent and the stove and the lantern and the rope and still forgot the matches."' },
    { term: 'Parallelism', category: 'rhetorical',
      definition: 'Repeating a grammatical structure across a sentence or passage to create balance and rhythm.',
      example: '"The team practiced daily, studied nightly, and improved weekly."' },
    { term: 'Anadiplosis', category: 'rhetorical',
      definition: 'Repeating the last word (or phrase) of one clause at the start of the next, chaining ideas together.',
      example: '"Practice builds skill; skill builds confidence; confidence wins close games."' },
    { term: 'Zeugma', category: 'rhetorical',
      definition: 'Using one word — often a verb — to govern two or more parts of a sentence in different, sometimes unexpected senses.',
      example: '"She caught the early bus and, somehow, my full attention."' },
    { term: 'Litotes', category: 'rhetorical',
      definition: 'A form of understatement that affirms something by negating its opposite.',
      example: '"The final exam was not exactly a walk in the park."' },
    { term: 'Hyperbole', category: 'rhetorical',
      definition: 'Deliberate, obvious exaggeration used for emphasis rather than to be taken literally.',
      example: '"I have told him a thousand times to lock the supply closet."' },
    { term: 'Understatement', category: 'rhetorical',
      definition: 'Describing something as less significant, intense, or serious than it actually is, often for ironic or dry effect.',
      example: '"We lost the championship by forty points — a minor setback, one supposes."' },
    { term: 'Rhetorical apostrophe', category: 'rhetorical',
      definition: 'Directly addressing an absent person, an abstract idea, or an inanimate object as though it could listen and respond.',
      example: '"Oh, patience, where have you wandered off to tonight?"' },
    { term: 'Concrete diction', category: 'rhetorical',
      definition: 'Word choice built from specific, tangible, sensory detail rather than vague or abstract terms.',
      example: 'Writing "the rusted hinge shrieked" instead of "the door made a bad noise."' },

    /* ---------- Argument & rhetorical appeals ---------- */
    { term: 'Ethos', category: 'argument',
      definition: 'A rhetorical appeal that establishes the speaker\'s credibility, expertise, or character to earn the audience\'s trust.',
      example: '"As a referee for twelve seasons, I can tell you that call was correct."' },
    { term: 'Pathos', category: 'argument',
      definition: 'A rhetorical appeal to the audience\'s emotions, meant to move them to feel something and, often, to act.',
      example: '"Picture the empty seat at graduation if the program gets cut."' },
    { term: 'Logos', category: 'argument',
      definition: 'A rhetorical appeal to logic and reasoning, typically built from facts, statistics, or a chain of evidence.',
      example: '"Attendance dropped forty percent the semester after the schedule changed — the data speaks for itself."' },
    { term: 'Kairos', category: 'argument',
      definition: 'A rhetorical appeal based on timing — the sense that the moment itself demands the argument be made now.',
      example: '"The vote happens tonight. There is no later train to catch."' },
    { term: 'Claim', category: 'argument',
      definition: 'The arguable position a writer is asking the audience to accept — the thesis the rest of the argument supports.',
      example: '"Standardized start times improve attendance" is a claim; a list of attendance figures is not.' },
    { term: 'Warrant', category: 'argument',
      definition: 'The often-unstated assumption or reasoning that connects a piece of evidence to the claim it is meant to support.',
      example: 'Citing rising test scores after a schedule change assumes the warrant that "more sleep improves academic performance."' },
    { term: 'Concession', category: 'argument',
      definition: 'Acknowledging that a point in the opposing argument has some validity before responding to it.',
      example: '"It\'s true the new policy costs more up front — but the long-term savings outweigh that cost."' },
    { term: 'Counterargument', category: 'argument',
      definition: 'The opposing position a writer anticipates, states fairly, and then addresses within their own argument.',
      example: 'Before defending a later start time, a writer summarizes the objection that it would shorten after-school practice.' },
    { term: 'Syllogism', category: 'argument',
      definition: 'A three-part logical argument made of a major premise, a minor premise, and a conclusion that necessarily follows.',
      example: '"All sophomores take Chemistry. Maria is a sophomore. Therefore, Maria takes Chemistry."' },
    { term: 'Straw man (fallacy)', category: 'argument',
      definition: 'Misrepresenting or oversimplifying an opponent\'s argument to make it easier to knock down.',
      example: 'Responding to "we should recycle more paper" with "so you want to ban all printing" attacks a position no one took.' },
    { term: 'Ad hominem (fallacy)', category: 'argument',
      definition: 'Attacking the character or motives of the person making an argument instead of engaging with the argument itself.',
      example: '"Why listen to her budget plan? She failed her own accounting class."' },
    { term: 'Slippery slope (fallacy)', category: 'argument',
      definition: 'Claiming that one small step will inevitably trigger a chain of increasingly extreme consequences, without justifying each link in the chain.',
      example: '"If we allow one late assignment, soon no one will ever turn anything in on time."' },
    { term: 'False dilemma (fallacy)', category: 'argument',
      definition: 'Presenting only two options as if they were the only possibilities, when other alternatives exist.',
      example: '"Either we cancel the field trip entirely, or we let anything happen." ignores every option in between.' },
    { term: 'Hasty generalization (fallacy)', category: 'argument',
      definition: 'Drawing a broad conclusion from a sample that is too small or too unrepresentative to support it.',
      example: '"I asked three friends and they all hated the cafeteria menu, so clearly the whole school hates it."' },
    { term: 'Circular reasoning (fallacy)', category: 'argument',
      definition: 'An argument that restates its conclusion as its own premise instead of offering independent support.',
      example: '"This rule is fair because it\'s the rule, and the rule is fair."' },

    /* ---------- Literary devices ---------- */
    { term: 'Imagery', category: 'literary',
      definition: 'Descriptive language that appeals to the senses — sight, sound, touch, taste, or smell — to make writing vivid.',
      example: '"The gym smelled of rubber and chalk, the bleachers still warm from the afternoon sun."' },
    { term: 'Symbolism', category: 'literary',
      definition: 'Using an object, person, or place to represent an idea or meaning beyond its literal function in the text.',
      example: 'A wilted team banner left hanging after a losing season can symbolize fading morale.' },
    { term: 'Motif', category: 'literary',
      definition: 'A recurring image, phrase, or situation that develops or reinforces a larger theme across a work.',
      example: 'Repeated references to locked doors throughout a story can build a motif of isolation.' },
    { term: 'Foreshadowing', category: 'literary',
      definition: 'Hints or clues planted earlier in a text that suggest what will happen later.',
      example: 'A character nervously double-checking a locked gate early on can foreshadow a break-in later.' },
    { term: 'Verbal irony', category: 'literary',
      definition: 'Saying one thing while meaning something else, often the opposite of the literal statement.',
      example: 'Calling a disastrous rehearsal "a real triumph" on the walk home.' },
    { term: 'Situational irony', category: 'literary',
      definition: 'An outcome that is the opposite of what was expected, given the circumstances.',
      example: 'The fire station catching fire during its own safety demonstration.' },
    { term: 'Dramatic irony', category: 'literary',
      definition: 'A gap between what the audience or reader knows and what a character in the story knows.',
      example: 'The audience watches a character walk toward a surprise party the character believes is an ordinary Tuesday.' },
    { term: 'Tone', category: 'literary',
      definition: 'The writer\'s or speaker\'s attitude toward the subject, conveyed mainly through word choice and sentence construction.',
      example: 'Describing a delay as "a minor scheduling hiccup" versus "an infuriating waste of everyone\'s afternoon" reveals very different tones toward the same event.' },
    { term: 'Mood', category: 'literary',
      definition: 'The atmosphere or emotional experience a passage creates for the reader, often built through setting and imagery.',
      example: 'Fog rolling over empty bleachers under a single working floodlight creates an eerie, uneasy mood.' },
    { term: 'Juxtaposition', category: 'literary',
      definition: 'Placing two sharply contrasting elements side by side so their differences stand out.',
      example: 'A description of the trophy case beside a description of the leaking ceiling above it.' },
    { term: 'Allegory', category: 'literary',
      definition: 'A narrative in which characters, objects, or events consistently represent abstract ideas or moral positions.',
      example: 'A story about a slow-moving team that overtakes a faster, arrogant rival can function as an allegory about persistence over talent.' },
    { term: 'Allusion', category: 'literary',
      definition: 'A brief reference to another work, historical event, or well-known figure that the reader is expected to recognize.',
      example: '"He walked in with the swagger of a modern-day Icarus" alludes to the myth without retelling it.' },
    { term: 'Foil', category: 'literary',
      definition: 'A character whose traits contrast with another character\'s traits, sharpening our sense of both by comparison.',
      example: 'A reckless, impulsive teammate makes a cautious, methodical captain\'s discipline stand out by contrast.' },
    { term: 'Characterization', category: 'literary',
      definition: 'The techniques a writer uses to reveal a character\'s traits — directly (the narrator states it) or indirectly (shown through action, speech, or others\' reactions).',
      example: 'Direct: "She was fiercely competitive." Indirect: she re-runs the same drill alone after the whole team has gone home.' },
    { term: 'Diction', category: 'literary',
      definition: 'A writer\'s specific word choices and the connotations those words carry.',
      example: 'Calling a strict coach "disciplined" versus "controlling" changes the reader\'s impression through diction alone.' },
    { term: 'Syntax', category: 'literary',
      definition: 'The arrangement and structure of words and sentences, used deliberately to create rhythm, emphasis, or effect.',
      example: 'A string of short, clipped sentences can convey panic; one long, winding sentence can convey a rambling, anxious thought.' },
    { term: 'Pathetic fallacy', category: 'literary',
      definition: 'Attributing human emotion to nature or weather so that the setting mirrors a character\'s inner state.',
      example: '"The sky darkened along with her mood as the last bus pulled away without her."' },
    { term: 'Epiphany', category: 'literary',
      definition: 'A character\'s sudden moment of insight or realization that shifts their understanding of themselves or their situation.',
      example: 'A character quits a sport mid-season, then realizes mid-argument that she was only ever playing to please her father.' },
    { term: 'Bildungsroman', category: 'literary',
      definition: 'A narrative genre centered on a protagonist\'s moral, psychological, or social development from youth toward maturity.',
      example: 'A novel that follows an anxious freshman through four years until she leads her own team as a confident senior.' },
    { term: 'Paradox', category: 'literary',
      definition: 'A statement that appears self-contradictory on its surface but reveals a deeper truth on reflection.',
      example: '"The more practices we canceled to rest up, the more tired the team became."' },

    /* ---------- Sound & poetic devices ---------- */
    { term: 'Alliteration', category: 'sound',
      definition: 'Repetition of initial consonant sounds in nearby words.',
      example: '"The crisp, cold crowd cheered as the clock counted down."' },
    { term: 'Assonance', category: 'sound',
      definition: 'Repetition of vowel sounds within nearby words, regardless of the consonants around them.',
      example: '"The light shined bright on the tired white lines of the track."' },
    { term: 'Consonance', category: 'sound',
      definition: 'Repetition of consonant sounds within or at the end of nearby words, without matching vowel sounds.',
      example: '"The blackened bricks flecked and cracked in the summer heat."' },
    { term: 'Onomatopoeia', category: 'sound',
      definition: 'A word that imitates or suggests the sound it describes.',
      example: 'The buzzer\'s harsh "BRAAAP" cut the game short a second before the shot fell.' },
    { term: 'Enjambment', category: 'sound',
      definition: 'Continuing a sentence or clause past the end of a poetic line without a pause or punctuation, pulling the reader forward.',
      example: 'A line ending mid-thought — "and still she ran / toward a finish line" — forces the eye onward without a break.' },
    { term: 'Caesura', category: 'sound',
      definition: 'A deliberate pause within a line of poetry, often marked by punctuation, that breaks its rhythm.',
      example: '"We waited. Watched. Nothing came." within a single line creates three small, deliberate stops.' },
    { term: 'Meter', category: 'sound',
      definition: 'The patterned rhythm of stressed and unstressed syllables that structures a line of poetry.',
      example: 'A steady da-DUM da-DUM da-DUM pattern across a line is iambic meter.' },
    { term: 'Personification', category: 'sound',
      definition: 'Giving human qualities, actions, or emotions to something nonhuman.',
      example: '"The old scoreboard groaned awake for one last game."' },
    { term: 'Metaphor', category: 'sound',
      definition: 'An implied comparison between two unlike things, stated as if one thing simply is the other.',
      example: '"The locker room was a pressure cooker before the final match."' },
    { term: 'Simile', category: 'sound',
      definition: 'An explicit comparison between two unlike things, typically using "like" or "as."',
      example: '"Her serve cracked across the net like a whip."' },
    { term: 'Synecdoche', category: 'sound',
      definition: 'Using a part of something to represent the whole, or the whole to represent a part.',
      example: '"All hands on deck for the fundraiser" uses "hands" to mean the whole team.' },
    { term: 'Metonymy', category: 'sound',
      definition: 'Referring to something by a term closely associated with it rather than its own name.',
      example: '"The front office finally approved the new uniforms," where "the front office" stands in for the administrators who work there.' },
    { term: 'Oxymoron', category: 'sound',
      definition: 'A phrase that joins two seemingly contradictory terms for effect.',
      example: '"Organized chaos" describes the locker room ten minutes before kickoff.' },

    /* ---------- Narrative elements & style ---------- */
    { term: 'Point of view', category: 'narrative',
      definition: 'The vantage point from which a story is told — first person (I), second person (you), or third person (he/she/they), limited or omniscient.',
      example: 'A memoir told as "I remember the smell of the gym" is first person; a novel narrating every character\'s private thoughts is third-person omniscient.' },
    { term: 'Unreliable narrator', category: 'narrative',
      definition: 'A narrator whose account is compromised — by bias, self-deception, limited knowledge, or dishonesty — so the reader must read against their version of events.',
      example: 'A narrator who insists he was always the better player, even as every detail he describes suggests otherwise.' },
    { term: 'Stream of consciousness', category: 'narrative',
      definition: 'A narrative style that mimics the continuous, associative, often unfiltered flow of a character\'s thoughts.',
      example: '"Warm-ups again already the whistle the same drill every single— did I even lock my bag—" renders thought as it actually happens, mid-leap.' },
    { term: 'In medias res', category: 'narrative',
      definition: 'Beginning a narrative in the middle of the action rather than at a chronological starting point, with earlier events filled in later.',
      example: 'A story opening on the final play of a championship game, before flashing back to the season that led there.' },
    { term: 'Denouement', category: 'narrative',
      definition: 'The final resolution of a narrative\'s action and conflicts, following the climax.',
      example: 'The quiet scene of the team packing up equipment after the championship has already been decided.' },
    { term: 'Frame narrative', category: 'narrative',
      definition: 'A story structure in which one narrative contains and introduces another story told within it.',
      example: 'A grandmother telling her grandchild about her own rookie season frames the season\'s story inside the present-day conversation.' },
    { term: 'Free indirect discourse', category: 'narrative',
      definition: 'Rendering a character\'s thoughts or speech in third person without an explicit marker like "she thought," blending narration and interiority.',
      example: '"She would not cry. Not here, not in front of the whole team." reads as narration but carries the character\'s own voice.' },
    { term: 'Epistolary', category: 'narrative',
      definition: 'A narrative told through a series of documents — letters, diary entries, texts, or similar records — rather than continuous prose narration.',
      example: 'A novel told entirely through a season\'s worth of a player\'s journal entries.' },
  ];

  window.APEnglish = {
    version: 1,
    categories: CATEGORIES,
    terms: TERMS,
  };
})();
