/* =====================================================================
   ap-packs.js  —  SkoolToolz · AP Flashcard Packs content module
   ---------------------------------------------------------------------
   Lazy-loaded on first open of the AP Flashcard Packs tool (mirrors the
   calculus-engine.js pattern), then cached. Loaded via a <script> tag so
   it also works from a local file:// copy.

   ALL CONTENT IS ORIGINAL, WRITTEN FOR SKOOLTOOLZ. Real AP exam questions
   and published study materials are copyrighted; nothing here is copied.
   These are plain-language term -> definition cards covering the most
   heavily tested concepts of each course, authored to match the level and
   scope of the exam without reproducing any source.

   Shape consumed by mountAPPacks():
     window.APPacks = {
       version,
       categories: [ { id, name } ],
       packs: [ { id, cat, icon, name, exam, blurb, cards: [ [front, back], ... ] } ]
     }
   ===================================================================== */
(function () {
  window.APPacks = {
    version: 1,

    categories: [
      { id: 'sci',    name: 'Sciences' },
      { id: 'hist',   name: 'History & Social Science' },
      { id: 'mathcs', name: 'Math & CS' }
    ],

    packs: [

      /* ============================ SCIENCES ============================ */

      {
        id: 'ap-bio', cat: 'sci', icon: '🧬', name: 'AP Biology', exam: 'AP Biology',
        blurb: 'Core terms across biochemistry, cells, energetics, genetics, evolution, and ecology.',
        cards: [
          ['Covalent bond', 'A chemical bond formed when two atoms share one or more pairs of electrons.'],
          ['Hydrogen bond', 'A weak attraction between a slightly positive hydrogen atom and a slightly negative atom (often O or N) on another molecule; gives water many of its properties.'],
          ['Hydrophobic', '"Water-fearing"; describes nonpolar substances that do not dissolve in water.'],
          ['pH', 'A measure of the hydrogen-ion concentration of a solution; lower pH is more acidic, higher is more basic.'],
          ['Polymer', 'A large molecule built from many repeating subunits (monomers) joined by dehydration synthesis.'],
          ['Enzyme', 'A biological catalyst (usually a protein) that speeds a reaction by lowering its activation energy without being used up.'],
          ['Activation energy', 'The minimum energy required to start a chemical reaction.'],
          ['ATP', 'Adenosine triphosphate, the cell’s main energy currency; energy is released when its terminal phosphate bond is broken.'],
          ['Phospholipid bilayer', 'The two-layer sheet of phospholipids that forms the basic structure of a cell membrane, with hydrophilic heads facing out and hydrophobic tails facing in.'],
          ['Selective permeability', 'The property of a membrane that lets some substances cross while blocking others.'],
          ['Diffusion', 'The net movement of molecules from an area of higher concentration to an area of lower concentration.'],
          ['Osmosis', 'The diffusion of water across a selectively permeable membrane.'],
          ['Active transport', 'Movement of a substance across a membrane against its concentration gradient, requiring energy (ATP).'],
          ['Mitochondrion', 'The organelle where cellular respiration produces most of a cell’s ATP.'],
          ['Chloroplast', 'The organelle in plants and algae where photosynthesis takes place.'],
          ['Cellular respiration', 'The process that breaks down glucose using oxygen to release energy stored as ATP (glycolysis, Krebs cycle, electron transport chain).'],
          ['Photosynthesis', 'The process by which plants convert light energy, water, and carbon dioxide into glucose and oxygen.'],
          ['Glycolysis', 'The breakdown of glucose into two pyruvate molecules in the cytoplasm, yielding a small amount of ATP; the first stage of respiration.'],
          ['Light-dependent reactions', 'The stage of photosynthesis in the thylakoid membranes that uses light to make ATP and NADPH and releases oxygen.'],
          ['Calvin cycle', 'The light-independent reactions of photosynthesis that use ATP and NADPH to build sugar from carbon dioxide.'],
          ['Mitosis', 'Nuclear division that produces two genetically identical diploid daughter cells, used for growth and repair.'],
          ['Meiosis', 'Cell division that produces four genetically varied haploid gametes from one diploid cell.'],
          ['Crossing over', 'The exchange of genetic material between homologous chromosomes during meiosis, increasing genetic variation.'],
          ['DNA replication', 'The semiconservative process by which a DNA molecule is copied, each original strand serving as a template.'],
          ['Transcription', 'The synthesis of an RNA copy (mRNA) from a DNA template.'],
          ['Translation', 'The synthesis of a protein at the ribosome using the codon sequence of mRNA.'],
          ['Codon', 'A sequence of three mRNA nucleotides that specifies one amino acid or a stop signal.'],
          ['Mutation', 'A change in the nucleotide sequence of DNA, which can be a source of genetic variation.'],
          ['Allele', 'One of the alternative versions of a gene.'],
          ['Genotype', 'The genetic makeup of an organism; the combination of alleles it carries.'],
          ['Phenotype', 'The observable physical or biochemical traits of an organism.'],
          ['Homozygous', 'Having two identical alleles for a given gene.'],
          ['Natural selection', 'The process by which individuals with favorable heritable traits tend to survive and reproduce more, shifting allele frequencies over generations.'],
          ['Genetic drift', 'Random change in allele frequencies in a population, most pronounced in small populations.'],
          ['Hardy-Weinberg equilibrium', 'A theoretical state in which allele and genotype frequencies stay constant because no evolutionary forces are acting.'],
          ['Negative feedback', 'A regulatory mechanism in which a change triggers a response that reverses the change, maintaining homeostasis.'],
          ['Trophic level', 'A feeding position in a food chain; only about 10% of energy passes from one level to the next.']
        ]
      },

      {
        id: 'ap-chem', cat: 'sci', icon: '⚗️', name: 'AP Chemistry', exam: 'AP Chemistry',
        blurb: 'Moles and stoichiometry, bonding, thermodynamics, kinetics, equilibrium, acids/bases, and redox.',
        cards: [
          ['Mole', 'The amount of a substance that contains 6.022 × 10²³ particles (Avogadro’s number).'],
          ['Avogadro’s number', '6.022 × 10²³, the number of particles in one mole.'],
          ['Molar mass', 'The mass in grams of one mole of a substance, numerically equal to its atomic or molecular mass in amu.'],
          ['Empirical formula', 'The simplest whole-number ratio of the atoms of each element in a compound.'],
          ['Molecular formula', 'The actual number of atoms of each element in a molecule.'],
          ['Stoichiometry', 'The use of balanced-equation mole ratios to calculate amounts of reactants and products.'],
          ['Limiting reactant', 'The reactant consumed first, which determines the maximum amount of product that can form.'],
          ['Theoretical yield', 'The maximum amount of product predicted by stoichiometry from the limiting reactant.'],
          ['Ionic bond', 'A bond formed by the electrostatic attraction between oppositely charged ions, typically a metal and a nonmetal.'],
          ['Covalent bond', 'A bond formed when two atoms share one or more pairs of electrons.'],
          ['Electronegativity', 'A measure of an atom’s tendency to attract bonding electrons; it increases up and to the right on the periodic table.'],
          ['Polar covalent bond', 'A covalent bond with unequal sharing of electrons because of an electronegativity difference.'],
          ['VSEPR theory', 'A model that predicts molecular shape based on the repulsion between electron domains around a central atom.'],
          ['Ideal gas law', 'PV = nRT, relating the pressure, volume, moles, and temperature of an ideal gas.'],
          ['Partial pressure', 'The pressure a gas in a mixture would exert if it alone occupied the container (Dalton’s law).'],
          ['Molarity', 'Concentration expressed as moles of solute per liter of solution (mol/L).'],
          ['Exothermic', 'Describes a reaction that releases energy to the surroundings; its ΔH is negative.'],
          ['Endothermic', 'Describes a reaction that absorbs energy from the surroundings; its ΔH is positive.'],
          ['Enthalpy (ΔH)', 'The heat content change of a reaction carried out at constant pressure.'],
          ['Hess’s law', 'The total enthalpy change of a reaction is the same no matter what pathway is taken.'],
          ['Entropy (S)', 'A measure of the disorder, or number of available microstates, of a system.'],
          ['Gibbs free energy (ΔG)', 'ΔG = ΔH − TΔS; a negative value means the process is spontaneous (thermodynamically favorable).'],
          ['Activation energy', 'The minimum energy needed for a reaction to occur.'],
          ['Catalyst', 'A substance that speeds a reaction by lowering its activation energy without being consumed.'],
          ['Rate law', 'An equation relating reaction rate to the concentrations of reactants raised to their reaction orders.'],
          ['Chemical equilibrium', 'The state in which the forward and reverse reaction rates are equal and concentrations remain constant.'],
          ['Le Châtelier’s principle', 'When a system at equilibrium is disturbed, it shifts to partially counteract the change.'],
          ['Equilibrium constant (K)', 'The ratio of product to reactant concentrations, each raised to its coefficient, at equilibrium.'],
          ['Arrhenius acid', 'A substance that increases the hydrogen-ion (hydronium) concentration in water.'],
          ['Brønsted-Lowry base', 'A proton (H⁺) acceptor.'],
          ['pH', 'Equal to −log[H⁺]; it measures acidity, with pH 7 neutral at 25°C.'],
          ['Buffer', 'A solution of a weak acid and its conjugate base (or vice versa) that resists changes in pH.'],
          ['Oxidation', 'The loss of electrons by a species, raising its oxidation number.'],
          ['Reduction', 'The gain of electrons by a species, lowering its oxidation number.'],
          ['Galvanic (voltaic) cell', 'An electrochemical cell that uses a spontaneous redox reaction to generate electrical energy.']
        ]
      },

      {
        id: 'ap-phys1', cat: 'sci', icon: '🪀', name: 'AP Physics 1', exam: 'AP Physics 1',
        blurb: 'Kinematics, Newton’s laws, energy, momentum, rotation, and simple harmonic motion.',
        cards: [
          ['Scalar', 'A quantity with magnitude only, such as speed, mass, or time.'],
          ['Vector', 'A quantity with both magnitude and direction, such as velocity or force.'],
          ['Displacement', 'The straight-line change in position from start to finish, with direction; a vector.'],
          ['Velocity', 'The rate of change of displacement; a vector (speed with a direction).'],
          ['Acceleration', 'The rate of change of velocity with respect to time.'],
          ['Newton’s first law', 'An object stays at rest or in uniform motion unless acted on by a net external force (the law of inertia).'],
          ['Newton’s second law', 'The net force on an object equals its mass times its acceleration (F = ma).'],
          ['Newton’s third law', 'For every force there is an equal and opposite reaction force.'],
          ['Inertia', 'The tendency of an object to resist changes in its state of motion; it is proportional to mass.'],
          ['Free-body diagram', 'A diagram showing all the forces acting on a single object as labeled arrows.'],
          ['Friction', 'A force that opposes the relative motion, or attempted motion, between surfaces in contact.'],
          ['Normal force', 'The support force a surface exerts perpendicular to an object resting on it.'],
          ['Weight', 'The gravitational force on an object, equal to mass times gravitational field strength (W = mg).'],
          ['Centripetal acceleration', 'The acceleration directed toward the center of a circular path, equal to v²/r.'],
          ['Centripetal force', 'The net inward force that keeps an object moving along a circular path.'],
          ['Work', 'The transfer of energy when a force moves an object; W = Fd·cosθ.'],
          ['Kinetic energy', 'The energy of motion, equal to ½mv².'],
          ['Potential energy', 'Stored energy due to position or configuration, such as gravitational PE = mgh.'],
          ['Conservation of energy', 'Energy cannot be created or destroyed, only transformed; total mechanical energy is constant when no friction acts.'],
          ['Power', 'The rate at which work is done or energy is transferred (P = W/t).'],
          ['Momentum', 'The product of an object’s mass and velocity (p = mv); a vector.'],
          ['Impulse', 'The change in momentum, equal to force times the time over which it acts (J = FΔt).'],
          ['Conservation of momentum', 'In the absence of external forces, the total momentum of a system stays constant.'],
          ['Elastic collision', 'A collision in which both momentum and kinetic energy are conserved.'],
          ['Inelastic collision', 'A collision in which momentum is conserved but kinetic energy is not.'],
          ['Torque', 'The rotational effect of a force, τ = rF·sinθ, which can cause angular acceleration.'],
          ['Rotational inertia', 'An object’s resistance to a change in its rotational motion, depending on how its mass is distributed.'],
          ['Angular velocity', 'The rate of change of angular position, measured in radians per second.'],
          ['Period', 'The time required for one complete cycle of periodic motion.'],
          ['Frequency', 'The number of cycles per second (hertz); the reciprocal of the period.'],
          ['Simple harmonic motion', 'Oscillation in which the restoring force is proportional to displacement, as for a mass on a spring.'],
          ['Hooke’s law', 'The force a spring exerts is proportional to its displacement (F = −kx).'],
          ['Mechanical wave', 'A disturbance that transfers energy through a medium without transferring matter.']
        ]
      },

      {
        id: 'ap-env', cat: 'sci', icon: '🌍', name: 'AP Environmental Science', exam: 'AP Environmental Science',
        blurb: 'Ecosystems, biogeochemical cycles, pollution, populations, and sustainability.',
        cards: [
          ['Ecosystem', 'A community of living organisms interacting with one another and with their nonliving environment.'],
          ['Biotic', 'Referring to the living components of an ecosystem.'],
          ['Abiotic', 'Referring to the nonliving physical and chemical factors of an ecosystem.'],
          ['Biodiversity', 'The variety of life in an area, including genetic, species, and ecosystem diversity.'],
          ['Keystone species', 'A species whose presence has a disproportionately large effect on its ecosystem.'],
          ['Primary succession', 'Ecological development that begins in a lifeless area with no soil, such as bare rock.'],
          ['Secondary succession', 'Ecological recovery in an area where a disturbance left the existing soil intact.'],
          ['Carrying capacity', 'The maximum population size that an environment can sustain indefinitely.'],
          ['Trophic level', 'A feeding level in a food chain; usable energy drops by roughly 90% between levels.'],
          ['Carbon cycle', 'The movement of carbon among the atmosphere, living organisms, oceans, and rocks.'],
          ['Nitrogen fixation', 'The conversion of atmospheric nitrogen gas into ammonia or nitrates usable by plants, carried out mainly by bacteria.'],
          ['Eutrophication', 'Nutrient over-enrichment of water that causes algal blooms and oxygen depletion.'],
          ['Greenhouse effect', 'The warming of Earth’s surface as atmospheric gases trap outgoing infrared radiation.'],
          ['Greenhouse gas', 'A gas such as carbon dioxide, methane, or water vapor that traps heat in the atmosphere.'],
          ['Renewable resource', 'A resource that is naturally replenished on a human timescale, such as solar or wind energy.'],
          ['Nonrenewable resource', 'A resource that exists in fixed amounts or forms too slowly to replace, such as fossil fuels.'],
          ['Fossil fuel', 'A carbon-rich fuel—coal, oil, or natural gas—formed from ancient organic matter.'],
          ['Ozone layer', 'A region of the stratosphere that absorbs most of the sun’s harmful ultraviolet radiation.'],
          ['Point-source pollution', 'Pollution that enters the environment from a single, identifiable source such as a pipe.'],
          ['Nonpoint-source pollution', 'Pollution from diffuse, hard-to-trace sources, such as agricultural runoff.'],
          ['Biomagnification', 'The increasing concentration of a toxin in organisms at successively higher trophic levels.'],
          ['Sustainable yield', 'The amount of a renewable resource that can be harvested without depleting the supply.'],
          ['Tragedy of the commons', 'The overuse of a shared resource by individuals acting in their own self-interest.'],
          ['Demographic transition', 'The shift of a population from high birth and death rates to low ones as a country industrializes.'],
          ['Total fertility rate', 'The average number of children a woman is expected to have in her lifetime.'],
          ['Watershed', 'The land area that drains into a particular river, lake, or other body of water.'],
          ['Salinization', 'The buildup of salts in soil, often caused by irrigation, that harms plant growth.'],
          ['Desertification', 'The degradation of once-fertile land into desert, often from drought and overuse.'],
          ['Acid rain', 'Precipitation made acidic by sulfur and nitrogen oxides released when fossil fuels burn.'],
          ['El Niño', 'A periodic warming of surface waters in the eastern Pacific that alters weather worldwide.'],
          ['Integrated pest management', 'A pest-control strategy that combines biological, chemical, and cultural methods to limit harm.'],
          ['Externality', 'A cost or benefit of an activity that falls on parties not directly involved in it.']
        ]
      },

      /* =================== HISTORY & SOCIAL SCIENCE =================== */

      {
        id: 'ap-ush', cat: 'hist', icon: '🦅', name: 'AP US History', exam: 'AP US History',
        blurb: 'Key terms, documents, and turning points from colonization through the modern era.',
        cards: [
          ['Columbian Exchange', 'The transatlantic transfer of plants, animals, people, and diseases that followed 1492.'],
          ['Mercantilism', 'An economic system in which colonies existed to enrich the mother country through tightly controlled trade.'],
          ['Mayflower Compact (1620)', 'An early agreement of self-government signed by the Pilgrims before landing.'],
          ['Great Awakening', 'A wave of emotional religious revival in the 1730s and 1740s.'],
          ['Salutary neglect', 'Britain’s loose enforcement of colonial trade laws before 1763.'],
          ['Declaration of Independence (1776)', 'The document, drafted by Jefferson, announcing the colonies’ separation from Britain and its natural-rights philosophy.'],
          ['Articles of Confederation', 'The first national framework of government, which created a deliberately weak central government.'],
          ['Constitutional Convention (1787)', 'The Philadelphia meeting that drafted the United States Constitution.'],
          ['Federalism', 'The division of power between a national government and the states.'],
          ['Bill of Rights', 'The first ten amendments to the Constitution, protecting individual liberties.'],
          ['Marbury v. Madison (1803)', 'The Supreme Court case that established the principle of judicial review.'],
          ['Louisiana Purchase (1803)', 'Jefferson’s acquisition of French territory that doubled the size of the United States.'],
          ['Manifest Destiny', 'The 19th-century belief that the United States was destined to expand across the continent.'],
          ['Missouri Compromise (1820)', 'An agreement admitting Missouri as a slave state and Maine as free and banning slavery north of 36°30′.'],
          ['Second Great Awakening', 'An early-1800s religious revival that helped fuel reform movements like abolition.'],
          ['Sectionalism', 'Loyalty to one’s region over the nation, especially North versus South over slavery.'],
          ['Compromise of 1850', 'A package of laws, including the Fugitive Slave Act, that admitted California as free and eased sectional tension.'],
          ['Emancipation Proclamation (1863)', 'Lincoln’s order declaring enslaved people in the rebelling states to be free.'],
          ['Reconstruction', 'The 1865–1877 era of rebuilding the South and integrating formerly enslaved people into national life.'],
          ['13th Amendment', 'The constitutional amendment that abolished slavery.'],
          ['Jim Crow laws', 'State and local laws that enforced racial segregation across the South.'],
          ['Gilded Age', 'The late-1800s era of rapid industrialization, concentrated wealth, and political corruption.'],
          ['Robber baron', 'A derogatory term for a powerful industrialist accused of unethical business practices.'],
          ['Progressive Era', 'An early-1900s reform movement targeting corruption, monopolies, and social problems.'],
          ['Imperialism', 'A policy of extending a nation’s power through colonization or military force, as in the Spanish-American War.'],
          ['Federal Reserve (1913)', 'The central banking system created to regulate the nation’s money supply.'],
          ['New Deal', 'Franklin Roosevelt’s 1930s programs for relief, recovery, and reform during the Great Depression.'],
          ['Great Depression', 'The severe economic downturn of the 1930s that followed the 1929 stock-market crash.'],
          ['Containment', 'The Cold War policy of stopping the spread of communism.'],
          ['Marshall Plan', 'The United States program of economic aid to rebuild Western Europe after World War II.'],
          ['McCarthyism', 'The early-1950s campaign of accusing people of communism, often without evidence.'],
          ['Brown v. Board of Education (1954)', 'The Supreme Court ruling that segregated public schools were unconstitutional.'],
          ['Civil Rights Act of 1964', 'Landmark law banning discrimination based on race, color, religion, sex, or national origin.'],
          ['Détente', 'The 1970s easing of Cold War tensions between the United States and the Soviet Union.'],
          ['Watergate', 'The 1970s scandal that led to President Nixon’s resignation.'],
          ['Cold War', 'The post-World War II geopolitical and ideological rivalry between the United States and the Soviet Union.']
        ]
      },

      {
        id: 'ap-wh', cat: 'hist', icon: '🌐', name: 'AP World History', exam: 'AP World History: Modern',
        blurb: 'Cross-regional concepts, trade networks, empires, and global change since c.1200.',
        cards: [
          ['Neolithic Revolution', 'The transition from hunting and gathering to settled agriculture, beginning around 10,000 BCE.'],
          ['Mandate of Heaven', 'The Chinese belief that heaven grants an emperor the right to rule based on his virtue.'],
          ['Silk Roads', 'The network of overland trade routes connecting East Asia to the Mediterranean.'],
          ['Bureaucracy', 'A system of government administration run by appointed officials.'],
          ['Confucianism', 'A Chinese philosophy emphasizing social harmony, respect for elders, and moral leadership.'],
          ['Diaspora', 'The dispersion of a people away from their original homeland.'],
          ['Caliphate', 'An Islamic state led by a caliph, regarded as a successor to the Prophet Muhammad.'],
          ['Feudalism', 'A medieval system of mutual obligations between lords and vassals in exchange for land and protection.'],
          ['Manorialism', 'The economic system of self-sufficient estates worked by peasants in medieval Europe.'],
          ['Crusades', 'A series of medieval religious wars launched by European Christians to control the Holy Land.'],
          ['Black Death', 'The 14th-century plague pandemic that killed a large share of Eurasia’s population.'],
          ['Renaissance', 'A 14th–17th century European rebirth of art and learning inspired by classical antiquity.'],
          ['Columbian Exchange', 'The transfer of crops, animals, people, and diseases between the Old and New Worlds after 1492.'],
          ['Mercantilism', 'An economic theory holding that a nation’s power depended on accumulating wealth through trade surpluses.'],
          ['Encomienda', 'A Spanish labor system granting colonists the right to demand labor from indigenous people.'],
          ['Triangular trade', 'The transatlantic trade network linking Europe, Africa, and the Americas, including enslaved people.'],
          ['Absolutism', 'A form of monarchy in which the ruler holds total, centralized power.'],
          ['Scientific Revolution', 'The 16th–17th century shift toward observation and reason in understanding the natural world.'],
          ['Enlightenment', 'An 18th-century intellectual movement emphasizing reason, liberty, and natural rights.'],
          ['Industrial Revolution', 'The late-1700s shift to machine-based manufacturing that transformed economies and societies.'],
          ['Capitalism', 'An economic system based on private ownership and market exchange for profit.'],
          ['Nationalism', 'Devotion to one’s nation, often expressed as a desire for self-rule or unity of a people.'],
          ['Imperialism', 'The policy of extending control over foreign territories, which peaked in the 19th century.'],
          ['Social Darwinism', 'The misapplication of “survival of the fittest” to justify imperialism and social inequality.'],
          ['Berlin Conference (1884–85)', 'The meeting at which European powers divided Africa among themselves.'],
          ['Total war', 'A war that mobilizes a nation’s entire economy and population, as in World War I.'],
          ['Communism', 'A system advocating common ownership and a classless society, based on Marxist theory.'],
          ['Fascism', 'An authoritarian, ultranationalist ideology that rose in interwar Europe.'],
          ['Decolonization', 'The post-World War II process by which colonies gained independence.'],
          ['Cold War', 'The ideological and geopolitical rivalry between the US-led and Soviet-led blocs after 1945.'],
          ['Non-Aligned Movement', 'A bloc of nations that refused to side with either superpower during the Cold War.'],
          ['Genocide', 'The deliberate, systematic destruction of a racial, ethnic, or religious group.'],
          ['Globalization', 'The growing interconnection of the world’s economies and cultures.'],
          ['Green Revolution', 'The mid-1900s spread of high-yield crops and modern farming that sharply raised food production.']
        ]
      },

      {
        id: 'ap-euro', cat: 'hist', icon: '🏰', name: 'AP European History', exam: 'AP European History',
        blurb: 'From the Renaissance and Reformation through revolutions, world wars, and integration.',
        cards: [
          ['Humanism', 'A Renaissance intellectual movement emphasizing classical texts and human potential.'],
          ['Renaissance', 'The 14th–17th century revival of art, learning, and classical ideals in Europe.'],
          ['Printing press', 'Gutenberg’s c.1450 invention that spread ideas rapidly and aided the Reformation.'],
          ['Protestant Reformation', 'The 16th-century movement, begun by Luther, that split Western Christianity.'],
          ['Ninety-Five Theses', 'Martin Luther’s 1517 list of objections to Catholic practices such as the sale of indulgences.'],
          ['Indulgence', 'A pardon sold by the Catholic Church that was said to reduce punishment for sins.'],
          ['Counter-Reformation', 'The Catholic Church’s internal reform and revival in response to Protestantism.'],
          ['Columbian Exchange', 'The transfer of goods, people, and diseases between Europe and the Americas after 1492.'],
          ['Absolutism', 'A system in which a monarch holds total sovereign power, as under Louis XIV.'],
          ['Divine right of kings', 'The doctrine that a monarch’s authority comes directly from God.'],
          ['Constitutionalism', 'A system in which government power is limited by law, as in England after 1688.'],
          ['Glorious Revolution (1688)', 'The nearly bloodless overthrow of James II that established parliamentary supremacy in England.'],
          ['Scientific Revolution', 'The 16th–17th century transformation of views of nature through observation and reason.'],
          ['Heliocentrism', 'The model, advanced by Copernicus, that places the sun at the center of the solar system.'],
          ['Enlightenment', 'An 18th-century movement championing reason, progress, and individual rights.'],
          ['Social contract', 'The Enlightenment idea that government derives its authority from an agreement among the people.'],
          ['Enlightened absolutism', 'Rule by monarchs who adopted Enlightenment reforms while keeping their absolute power.'],
          ['French Revolution (1789)', 'The upheaval that overthrew the French monarchy and proclaimed liberty and equality.'],
          ['Reign of Terror', 'The radical, violent phase of the French Revolution led by Robespierre.'],
          ['Nationalism', 'Devotion to one’s nation, a powerful force in 19th-century European politics.'],
          ['Industrial Revolution', 'The shift to mechanized factory production that began in Britain around 1750.'],
          ['Liberalism', 'A 19th-century ideology favoring individual liberty, constitutional government, and free markets.'],
          ['Conservatism', 'A 19th-century ideology defending traditional institutions, monarchy, and social order.'],
          ['Congress of Vienna (1815)', 'The conference that redrew Europe’s map and restored order after Napoleon.'],
          ['Unification of Germany', 'The 1871 creation of a German nation-state, engineered largely by Bismarck.'],
          ['Realpolitik', 'Practical politics based on power and national interest rather than ideology.'],
          ['Imperialism', 'The late-1800s European drive to acquire overseas colonies.'],
          ['World War I', 'The 1914–1918 conflict triggered by alliances, nationalism, and militarism.'],
          ['Russian Revolution (1917)', 'The uprising that toppled the tsar and brought the Bolsheviks to power.'],
          ['Totalitarianism', 'A system in which the state seeks total control over public and private life.'],
          ['Appeasement', 'The 1930s policy of conceding to Hitler’s demands in the hope of avoiding war.'],
          ['Holocaust', 'The Nazi genocide of six million Jews and millions of others during World War II.'],
          ['European Union', 'The post-World War II political and economic union promoting integration among member states.']
        ]
      },

      {
        id: 'ap-psych', cat: 'hist', icon: '🧠', name: 'AP Psychology', exam: 'AP Psychology',
        blurb: 'Research methods, biology, learning, cognition, development, and disorders.',
        cards: [
          ['Independent variable', 'The factor a researcher deliberately manipulates in an experiment.'],
          ['Dependent variable', 'The outcome that is measured in an experiment.'],
          ['Placebo effect', 'Improvement caused by a person’s expectation rather than by an actual treatment.'],
          ['Neuron', 'A nerve cell that transmits electrical and chemical signals in the nervous system.'],
          ['Synapse', 'The junction across which one neuron passes a signal to another cell.'],
          ['Neurotransmitter', 'A chemical messenger that crosses the synapse to influence the next neuron.'],
          ['Action potential', 'A brief electrical impulse that travels down a neuron’s axon.'],
          ['Amygdala', 'A brain structure involved in processing emotions, especially fear.'],
          ['Hippocampus', 'A brain structure essential for forming new long-term memories.'],
          ['Cerebral cortex', 'The brain’s wrinkled outer layer, responsible for higher mental functions.'],
          ['Plasticity', 'The brain’s ability to change and reorganize by forming new neural connections.'],
          ['Classical conditioning', 'Learning to associate two stimuli so that one triggers a response, as in Pavlov’s dogs.'],
          ['Operant conditioning', 'Learning in which behavior is shaped by rewards and punishments, as studied by Skinner.'],
          ['Reinforcement', 'Any consequence that strengthens the behavior it follows.'],
          ['Negative reinforcement', 'Strengthening a behavior by removing an unpleasant stimulus.'],
          ['Observational learning', 'Learning by watching and imitating others, as shown in Bandura’s research.'],
          ['Sensation', 'The detection of physical stimuli by sensory receptors.'],
          ['Perception', 'The brain’s organization and interpretation of sensory information.'],
          ['Absolute threshold', 'The minimum stimulus intensity a person can detect 50% of the time.'],
          ['Working memory', 'The active system that briefly holds and manipulates information.'],
          ['Long-term memory', 'The relatively permanent and seemingly limitless store of information.'],
          ['Encoding', 'The process of getting information into memory.'],
          ['Retrieval', 'The process of getting information back out of memory.'],
          ['Schema', 'A mental framework that organizes and interprets information.'],
          ['Confirmation bias', 'The tendency to seek out information that supports one’s existing beliefs.'],
          ['Availability heuristic', 'Judging how likely an event is by how easily examples come to mind.'],
          ['Intelligence quotient (IQ)', 'A score from standardized tests intended to measure mental ability.'],
          ['Maslow’s hierarchy of needs', 'A pyramid ranking human needs from basic survival up to self-actualization.'],
          ['Drive-reduction theory', 'The idea that physiological needs create drives that motivate behavior to restore balance.'],
          ['Circadian rhythm', 'The body’s roughly 24-hour cycle of biological activity, including the sleep-wake cycle.'],
          ['Conformity', 'Adjusting one’s behavior or thinking to match a group standard, as in Asch’s experiments.'],
          ['Fundamental attribution error', 'Overestimating personality and underestimating the situation when explaining others’ behavior.'],
          ['Cognitive dissonance', 'The discomfort of holding conflicting beliefs or behaviors, which motivates change.'],
          ['Psychoanalysis', 'Freud’s theory and therapy emphasizing the unconscious mind and early experiences.'],
          ['Major depressive disorder', 'A mood disorder marked by persistent sadness and loss of interest.'],
          ['Generalized anxiety disorder', 'A disorder of chronic, excessive, hard-to-control worry.']
        ]
      },

      {
        id: 'ap-hug', cat: 'hist', icon: '🗺️', name: 'AP Human Geography', exam: 'AP Human Geography',
        blurb: 'Spatial concepts, population, culture, political geography, agriculture, and cities.',
        cards: [
          ['Geographic Information System (GIS)', 'A computer system for capturing, storing, and analyzing spatial data.'],
          ['Distance decay', 'The weakening of a phenomenon’s influence as distance from its source increases.'],
          ['Friction of distance', 'The idea that distance takes time, effort, or cost to overcome.'],
          ['Diffusion', 'The spread of a phenomenon across space and over time.'],
          ['Hierarchical diffusion', 'Spread from larger or more powerful places down to smaller ones.'],
          ['Relocation diffusion', 'Spread carried by people physically moving from one place to another.'],
          ['Demographic transition model', 'A model describing population change as a country develops through stages.'],
          ['Total fertility rate', 'The average number of children a woman is expected to bear in her lifetime.'],
          ['Population pyramid', 'A graph showing the age and sex structure of a population.'],
          ['Carrying capacity', 'The number of people an environment can support sustainably.'],
          ['Push factor', 'A condition that drives people to leave a place.'],
          ['Pull factor', 'A condition that attracts people to a new place.'],
          ['Chain migration', 'Migration to a place where relatives or compatriots have already settled.'],
          ['Folk culture', 'Traditional culture practiced by small, homogeneous groups in relatively isolated areas.'],
          ['Popular culture', 'Widespread culture shared by large, heterogeneous, often globalized populations.'],
          ['Lingua franca', 'A common language adopted so speakers of different languages can communicate.'],
          ['Cultural landscape', 'The visible imprint of human activity on the environment.'],
          ['Toponym', 'The name given to a place.'],
          ['Nation-state', 'A state whose territory corresponds to that of a single cultural nation.'],
          ['Centripetal force', 'A factor that unifies and binds a state together.'],
          ['Centrifugal force', 'A factor that divides people and can destabilize a state.'],
          ['Gerrymandering', 'Drawing voting-district boundaries to favor a particular group.'],
          ['Von Thünen model', 'A model explaining agricultural land use based on distance to the market.'],
          ['Green Revolution', 'The spread of high-yield seeds and modern techniques that raised crop output.'],
          ['Agribusiness', 'The large-scale, commercialized system of food production and distribution.'],
          ['Central place theory', 'Christaller’s model explaining the size and spacing of settlements and their services.'],
          ['Primate city', 'A country’s largest city, far bigger than the next and dominant in the nation’s life.'],
          ['Rank-size rule', 'A pattern in which a country’s nth-largest city is about 1/n the size of its largest.'],
          ['Urbanization', 'The increasing share of a population living in cities.'],
          ['Suburbanization', 'The growth of areas surrounding cities as people move outward.'],
          ['Site', 'The internal physical characteristics of a place, such as its terrain or climate.'],
          ['Situation', 'A place’s location relative to other places.'],
          ['Sustainable development', 'Development that meets present needs without compromising future generations.'],
          ['Sovereignty', 'A state’s right to govern itself without outside interference.']
        ]
      },

      {
        id: 'ap-gov', cat: 'hist', icon: '🏛️', name: 'AP US Government & Politics', exam: 'AP US Government and Politics',
        blurb: 'Foundational principles, the Constitution, branches, civil liberties, and political behavior.',
        cards: [
          ['Federalism', 'The division of power between the national government and the states.'],
          ['Separation of powers', 'The division of government into legislative, executive, and judicial branches.'],
          ['Checks and balances', 'The system by which each branch can limit the powers of the others.'],
          ['Popular sovereignty', 'The principle that the government’s authority comes from the consent of the people.'],
          ['Republicanism', 'A system in which people elect representatives to govern on their behalf.'],
          ['Federalist No. 10', 'Madison’s essay arguing that a large republic best controls the harmful effects of factions.'],
          ['Federalist No. 51', 'Madison’s essay defending separation of powers and checks and balances.'],
          ['Brutus No. 1', 'An Anti-Federalist essay warning that a large central government would threaten liberty.'],
          ['Bill of Rights', 'The first ten amendments, which protect individual liberties.'],
          ['Selective incorporation', 'The process of applying Bill of Rights protections to the states through the 14th Amendment.'],
          ['Establishment clause', 'The First Amendment clause barring the government from establishing a religion.'],
          ['Free exercise clause', 'The First Amendment clause protecting the practice of religion.'],
          ['Due process clause', 'A constitutional guarantee that the government must respect fair legal procedures.'],
          ['Equal protection clause', 'The 14th Amendment clause requiring states to treat people equally under the law.'],
          ['Judicial review', 'The power of courts to strike down laws or actions that violate the Constitution.'],
          ['Marbury v. Madison (1803)', 'The case that established the power of judicial review.'],
          ['McCulloch v. Maryland (1819)', 'The case affirming implied powers and national supremacy over the states.'],
          ['Necessary and proper clause', 'The clause giving Congress implied powers to carry out its enumerated duties.'],
          ['Commerce clause', 'The clause granting Congress the power to regulate interstate commerce.'],
          ['Filibuster', 'A Senate tactic of prolonged debate used to delay or block a vote.'],
          ['Cloture', 'A Senate procedure to end a filibuster, requiring 60 votes.'],
          ['Pork-barrel spending', 'Government spending directed to a legislator’s home district for local benefit.'],
          ['Veto', 'The president’s power to reject a bill passed by Congress.'],
          ['Executive order', 'A directive issued by the president that carries the force of law.'],
          ['Bureaucracy', 'The system of federal agencies and departments that carry out and enforce laws.'],
          ['Iron triangle', 'The stable alliance among an agency, a congressional committee, and an interest group.'],
          ['Stare decisis', 'The judicial principle of deciding cases according to precedent.'],
          ['Political party', 'An organization that seeks to win elections and control government.'],
          ['Linkage institution', 'A channel, such as parties or the media, that connects citizens to their government.'],
          ['Interest group', 'An organization that seeks to influence public policy on specific issues.'],
          ['Political action committee (PAC)', 'An organization that raises and spends money to help elect candidates.'],
          ['Electoral College', 'The body that formally elects the president based on each state’s electoral votes.'],
          ['Incumbency advantage', 'The electoral edge enjoyed by current officeholders seeking reelection.'],
          ['Civil liberties', 'Constitutional protections of individuals from government overreach.'],
          ['Civil rights', 'Protections against discrimination that guarantee equal treatment under the law.']
        ]
      },

      /* ========================= MATH & CS ========================= */

      {
        id: 'ap-calc', cat: 'mathcs', icon: '∫', name: 'AP Calculus AB/BC', exam: 'AP Calculus AB & BC',
        blurb: 'Limits, derivatives, integrals, and the FTC, plus BC topics (parts, series, parametrics).',
        cards: [
          ['Limit', 'The value a function approaches as its input approaches a given point.'],
          ['Continuity', 'A function is continuous at a point if its limit there equals its value, with no break or jump.'],
          ['Derivative', 'The instantaneous rate of change of a function; the slope of its tangent line.'],
          ['Difference quotient', 'The expression [f(x+h) − f(x)]/h, whose limit as h→0 defines the derivative.'],
          ['Power rule', 'The derivative of xⁿ is n·xⁿ⁻¹.'],
          ['Product rule', 'The derivative of f·g is f′g + fg′.'],
          ['Quotient rule', 'The derivative of f/g is (f′g − fg′)/g².'],
          ['Chain rule', 'The derivative of a composite f(g(x)) is f′(g(x))·g′(x).'],
          ['Implicit differentiation', 'Differentiating an equation not solved for y, treating y as a function of x.'],
          ['Critical point', 'A point where a function’s derivative is zero or undefined.'],
          ['Local maximum', 'A point where a function’s value is greater than at all nearby points.'],
          ['Inflection point', 'A point where a curve changes concavity.'],
          ['Concavity', 'Whether a curve bends upward or downward, determined by the sign of the second derivative.'],
          ['Mean Value Theorem', 'If f is continuous on [a,b] and differentiable on (a,b), some c has f′(c) equal to the average rate of change.'],
          ['Related rates', 'Problems that link the rates of change of two or more quantities through a shared equation.'],
          ['Antiderivative', 'A function whose derivative is the given function; the reverse of differentiation.'],
          ['Indefinite integral', 'The family of all antiderivatives of a function, written with a constant +C.'],
          ['Definite integral', 'The signed area under a curve between two bounds.'],
          ['Fundamental Theorem of Calculus', 'Links differentiation and integration: the definite integral of f′ from a to b equals f(b) − f(a).'],
          ['Riemann sum', 'An approximation of a definite integral by adding up the areas of rectangles.'],
          ['u-substitution', 'An integration technique that reverses the chain rule by substituting in a new variable.'],
          ['Integration by parts', 'A BC technique based on the product rule: ∫u dv = uv − ∫v du.'],
          ['Average value of a function', 'Equal to (1/(b−a)) times the definite integral of f(x) from a to b.'],
          ['Disk method', 'Finding a volume of revolution by integrating the areas of circular cross-sections.'],
          ['Differential equation', 'An equation involving a function together with one or more of its derivatives.'],
          ['Slope field', 'A graph of short line segments showing the solutions of a first-order differential equation.'],
          ['Exponential growth', 'Growth modeled by dy/dt = ky, giving y = y₀e^{kt}.'],
          ['L’Hôpital’s rule', 'A method for evaluating indeterminate-form limits by differentiating the numerator and denominator.'],
          ['Parametric equations', 'BC topic: equations expressing the coordinates of a curve as functions of a parameter.'],
          ['Polar coordinates', 'BC topic: a system that locates points by a radius and an angle.'],
          ['Sequence', 'BC topic: an ordered list of numbers.'],
          ['Series', 'BC topic: the sum of the terms of a sequence.'],
          ['Taylor series', 'BC topic: a representation of a function as an infinite polynomial expanded about a point.'],
          ['Ratio test', 'BC topic: a test for the convergence of a series using the limit of consecutive term ratios.'],
          ['Convergence', 'BC topic: the property of a sequence or series approaching a finite limit.']
        ]
      },

      {
        id: 'ap-stat', cat: 'mathcs', icon: '📊', name: 'AP Statistics', exam: 'AP Statistics',
        blurb: 'Exploring data, sampling and experiments, probability, and inference.',
        cards: [
          ['Population', 'The entire group of individuals about which we want information.'],
          ['Sample', 'The subset of a population from which data are actually collected.'],
          ['Parameter', 'A numerical summary of a population, which is usually unknown.'],
          ['Statistic', 'A numerical summary of a sample, used to estimate a parameter.'],
          ['Categorical variable', 'A variable that sorts individuals into groups or categories.'],
          ['Quantitative variable', 'A variable that takes numerical values for which arithmetic makes sense.'],
          ['Mean', 'The arithmetic average of a set of values.'],
          ['Median', 'The middle value of an ordered data set.'],
          ['Standard deviation', 'A measure of the typical distance of values from the mean.'],
          ['Interquartile range', 'The range of the middle 50% of the data, equal to Q3 − Q1.'],
          ['Outlier', 'A data value that lies unusually far from the rest.'],
          ['Skewed distribution', 'A distribution with a longer tail on one side than the other.'],
          ['Normal distribution', 'A symmetric, bell-shaped distribution defined by its mean and standard deviation.'],
          ['Empirical rule', 'In a normal distribution, about 68%, 95%, and 99.7% of data lie within 1, 2, and 3 standard deviations of the mean.'],
          ['z-score', 'The number of standard deviations a value lies above or below the mean.'],
          ['Correlation coefficient (r)', 'A measure of the strength and direction of a linear relationship, ranging from −1 to 1.'],
          ['Least-squares regression line', 'The line that minimizes the sum of the squared residuals between data and predictions.'],
          ['Residual', 'The difference between an observed value and the value predicted by a model.'],
          ['Coefficient of determination (r²)', 'The proportion of the variation in y explained by the linear model.'],
          ['Simple random sample', 'A sample chosen so every group of the given size has an equal chance of being selected.'],
          ['Stratified sample', 'A sample formed by dividing the population into strata and sampling within each one.'],
          ['Bias', 'A systematic error that pushes results consistently in one direction.'],
          ['Confounding variable', 'A variable that affects the response and is tangled up with the explanatory variable.'],
          ['Experiment', 'A study that imposes treatments on subjects to observe the effect on a response.'],
          ['Observational study', 'A study that observes individuals without imposing any treatment.'],
          ['Control group', 'A baseline group that does not receive the treatment, used for comparison.'],
          ['Placebo', 'A fake treatment used to control for the psychological effect of being treated.'],
          ['Random variable', 'A variable whose value is a numerical outcome of a random process.'],
          ['Probability', 'A number between 0 and 1 that expresses how likely an event is.'],
          ['Sampling distribution', 'The distribution of a statistic over all possible samples of a given size.'],
          ['Central Limit Theorem', 'The sampling distribution of the sample mean approaches a normal shape as the sample size grows.'],
          ['Confidence interval', 'A range of plausible values for a parameter, reported with a confidence level.'],
          ['Null hypothesis', 'The default claim of no effect or no difference that is being tested.'],
          ['p-value', 'The probability of getting a result at least as extreme as the one observed if the null hypothesis is true.'],
          ['Statistical significance', 'A result unlikely to have occurred by chance, leading to rejection of the null hypothesis.']
        ]
      },

      {
        id: 'ap-csp', cat: 'mathcs', icon: '💻', name: 'AP CS Principles', exam: 'AP Computer Science Principles',
        blurb: 'Programming concepts, data, the internet, and the impact of computing.',
        cards: [
          ['Algorithm', 'A finite, step-by-step procedure for solving a problem or completing a task.'],
          ['Abstraction', 'The practice of hiding complex details in order to focus on higher-level ideas.'],
          ['Variable', 'A named storage location that holds a value which can change.'],
          ['Boolean', 'A data type with only two possible values: true and false.'],
          ['Conditional (selection)', 'A programming structure that runs a block of code only if a condition is met.'],
          ['Iteration (loop)', 'A structure that repeats a block of code.'],
          ['Procedure (function)', 'A named, reusable block of code that performs a task and can take parameters.'],
          ['Parameter', 'An input variable that lets a procedure work on different values each time it runs.'],
          ['List', 'An ordered collection of values stored under one name and accessed by index.'],
          ['API', 'An application programming interface; a set of procedures for building software.'],
          ['Bit', 'The smallest unit of data, a single binary digit (0 or 1).'],
          ['Byte', 'A group of 8 bits.'],
          ['Binary', 'A base-2 number system that uses only 0s and 1s, the basis of digital data.'],
          ['Analog data', 'Data with continuous values, as opposed to discrete digital data.'],
          ['Lossless compression', 'Reducing the size of data so the original can be perfectly reconstructed.'],
          ['Lossy compression', 'Reducing the size of data by discarding some information, which cannot be fully recovered.'],
          ['Overflow error', 'An error that occurs when a number is too large for the storage allotted to it.'],
          ['Round-off error', 'An error caused by representing a number with limited precision.'],
          ['Internet', 'A global network of interconnected networks that communicate using shared protocols.'],
          ['Protocol', 'An agreed-upon set of rules that governs how devices exchange data.'],
          ['IP address', 'A unique numeric label that identifies a device on a network.'],
          ['Packet', 'A small unit of data transmitted over a network.'],
          ['Redundancy', 'Including backup paths or copies so a system keeps working if part of it fails.'],
          ['Fault tolerance', 'A system’s ability to keep functioning even when some components fail.'],
          ['Bandwidth', 'The maximum amount of data a network can transmit per unit of time.'],
          ['Encryption', 'Encoding data so that only authorized parties can read it.'],
          ['Public key encryption', 'A method that uses a public key to encrypt data and a private key to decrypt it.'],
          ['Phishing', 'A scam that tricks people into revealing sensitive information by posing as a trustworthy source.'],
          ['Sequencing', 'Carrying out the steps of a program in a specific order.'],
          ['Heuristic', 'A practical approach that finds a good-enough solution when an exact one is impractical.'],
          ['Undecidable problem', 'A problem for which no algorithm can always produce a correct yes-or-no answer.'],
          ['Digital divide', 'The gap between those who have access to computing technology and those who do not.'],
          ['Citizen science', 'Public participation in scientific data collection, enabled by computing.'],
          ['Personally identifiable information (PII)', 'Data that can be used to identify a specific individual.']
        ]
      }

    ]
  };
})();
